blockFields:
- id: ProductsLinkList
  type: Pointer
  name:
    en-US: Products
    sv-SE: Produkter
  settings:
    multiCulture: false
    administration:
      columns: false
      filter: false
      readonly: false
    storefront:
      visible: true
      searchable: false
  option:
    entityType: ProductsProduct
    multiSelect: true
